language: csharp
solution: SampleWebAPI.sln
install:
  - nuget restore SampleWebAPI.sln
  - nuget install NUnit.Console - Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release SampleWebAPI.sln
  - ls
  - echo 'Build Complete'