language: csharp
solution: SampleWebAPI.sln
install:
  - nuget restore SampleWebAPI.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release SampleWebAPI.sln
  - echo 'Build Completed'
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./SampleWebAPITests/bin/Release/SampleWebAPITests.dll
  - echo 'Testing Completed'
deploy:
  provider: azure_web_apps
  on: main
  verbose: true